// 知识小卡片 —— 双语术语表。课程正文里出现这些关键概念时，渲染器会自动给它加一条
// 虚线下划线，鼠标 hover / 键盘聚焦即弹出释义卡。每个条目：{ zh:{n:[匹配词…], d:释义 }, en:{…} }。
// n[0] 为卡片标题（规范写法），其余为别名/同义词；ASCII 词按词边界大小写精确匹配，中文按子串匹配。
// 所以：ASCII 的单复数/变形要各写一条（security 与 securities 不互相匹配）；中文别名务必够长够专——
// “基金”“市场”这类通用词会在全文乱开花，宁可写“货币市场基金”“二级市场”。同一概念每块正文只标注首次出现处。
// 释义一句话讲透，贴课程主线：代币只是一张收据，信任真正住在链下的结构里。
// 加词只改这个文件 + bump glossary.js?v 与 app.js?v，不动任何课文。

export const GLOSSARY = [
  // —— 资产与金融 ——
  { zh:{n:["RWA","真实世界资产"],d:"Real-World Asset：把国债、信贷、地产、黄金这类链下资产的权益做成链上代币——资产仍在现实里，代币只是收据。"},
    en:{n:["RWA","real-world asset","real-world assets"],d:"Real-World Asset: an on-chain token carrying a claim on an off-chain asset — Treasuries, credit, property, gold. The asset stays in the real world; the token is the receipt."} },
  { zh:{n:["代币化"],d:"把一份法律上的权益登记搬上链、用代币余额表示，从而可分割、可编程、可 7×24 转移——难点从来不在发币，在链下结构。"},
    en:{n:["tokenization","tokenized","tokenize"],d:"Moving a legal ownership record onto a chain so it becomes divisible, programmable, and transferable 24/7. Minting is the easy part; the off-chain structure is the hard part."} },
  { zh:{n:["T-Bill","短期国债","国库券"],d:"美国财政部一年内到期的短期债，被视为无风险利率的锚——RWA 里体量最大、最容易上链的底层资产。"},
    en:{n:["T-Bill","T-bill","Treasury bill"],d:"A US Treasury obligation maturing within a year, the anchor of the risk-free rate — the largest and most tokenizable asset class in RWA."} },
  { zh:{n:["货币市场基金","MMF"],d:"只投短期高信用债务、力求每份净值稳定的基金，是绝大多数代币化国债产品链下真正持有的东西。"},
    en:{n:["money market fund","money market funds","MMF"],d:"A fund holding only short-dated, high-grade debt and aiming to keep share value stable — what most tokenized Treasury products actually hold off-chain."} },
  { zh:{n:["NAV","资产净值"],d:"Net Asset Value：（总资产−负债）÷份额数，一份基金值多少钱。链上价格若长期偏离 NAV，说明赎回通道不畅。"},
    en:{n:["NAV","net asset value"],d:"(Assets − liabilities) ÷ shares: what one fund share is worth. A token price that drifts from NAV for long means the redemption channel is clogged."} },
  { zh:{n:["票息"],d:"债券按面值定期支付的利息。上链后要么派发成新代币，要么累积进份额价格——两条路的税务与合约友好度完全不同。"},
    en:{n:["coupon","coupons"],d:"The periodic interest a bond pays on its face value. On-chain it's either distributed as new tokens or accrued into the share price — with very different tax and integration consequences."} },
  { zh:{n:["DvP","券款对付"],d:"Delivery versus Payment：券和钱同时易手，任一腿失败则整笔回滚——原子结算是代币化最硬的技术优势。"},
    en:{n:["DvP","delivery versus payment"],d:"Delivery versus Payment: security and cash change hands simultaneously; if either leg fails, the whole trade unwinds. Atomic settlement is tokenization's hardest technical edge."} },
  { zh:{n:["T+1"],d:"成交后第一个工作日才完成交割的传统结算节奏——中间那一天的对手方风险与保证金占用，正是链上原子结算要消灭的东西。"},
    en:{n:["T+1"],d:"Traditional settlement: the trade closes one business day after execution. The counterparty risk and margin locked up during that day are what atomic settlement targets."} },
  { zh:{n:["私募信贷"],d:"绕开公开市场、直接借给企业的非上市贷款：收益高、透明度低、几乎无二级市场；包成代币也改不掉底层违约风险。"},
    en:{n:["private credit"],d:"Non-public loans made directly to companies: higher yield, lower transparency, almost no secondary market. Wrapping it on-chain doesn't touch the underlying default risk."} },
  { zh:{n:["证券"],d:"对他人经营成果的可投资权益凭证（股、债、基金份额）。是不是证券由实质决定，套一层代币不改变结论。"},
    en:{n:["security","securities"],d:"An investable claim on someone else's enterprise — stock, bond, fund share. Whether something is a security turns on substance; a token wrapper changes nothing."} },
  { zh:{n:["合格投资者"],d:"美国 Reg D 下按收入或净资产划线的私募准入门槛（个人约 20 万美元年收入或 100 万净资产，不含自住房）。"},
    en:{n:["accredited investor","accredited investors"],d:"The US Reg D eligibility bar set by income or net worth (roughly $200k annual income or $1M net worth excluding one's home) for buying private offerings."} },

  // —— 结构与法律 ——
  { zh:{n:["SPV","特殊目的载体"],d:"专为持有某项资产而设、除此之外什么都不干的空壳法人；代币持有人的请求权最终落在它身上，而不是发行方本体。"},
    en:{n:["SPV","SPVs","special purpose vehicle"],d:"A shell entity created to hold one asset and do nothing else. Token holders' claim lands on the SPV, not on the sponsor's balance sheet."} },
  { zh:{n:["破产隔离"],d:"把资产真实出售给独立法人，使发起方倒闭时其债权人够不到它——这是整个 RWA 结构的承重墙，也是尽调第一问。"},
    en:{n:["bankruptcy remoteness","bankruptcy remote"],d:"Truly selling the asset into a separate entity so the sponsor's creditors can't reach it if the sponsor fails — the load-bearing wall of every RWA structure."} },
  { zh:{n:["真实出售"],d:"资产必须在法律上真正卖给 SPV（而非抵押给它），破产法庭才不会把它拉回原发起方的财产池。"},
    en:{n:["true sale"],d:"The asset must be legally sold to the SPV, not pledged to it — otherwise a bankruptcy court can pull it back into the originator's estate."} },
  { zh:{n:["PPM","私募备忘录"],d:"Private Placement Memorandum：私募发行的核心披露文件，风险因素、费用、赎回条款都在里面——尽调先读它，别读官网。"},
    en:{n:["PPM","private placement memorandum"],d:"The core disclosure document for a private offering: risk factors, fees, redemption terms. Start diligence here, not on the marketing site."} },
  { zh:{n:["转让代理"],d:"官方维护持有人名册、办理过户与分派的持牌机构。代币化的实质，往往就是让智能合约兼任这个角色。"},
    en:{n:["transfer agent","transfer agents"],d:"The licensed entity that maintains the official holder register and processes transfers and distributions. Tokenization often just means a smart contract doing this job."} },
  { zh:{n:["行政管理人","基金行政管理人"],d:"独立第三方，负责估值、算 NAV、记份额、出对账单——链上 NAV 喂价的源头基本都是它，不是发行方自己。"},
    en:{n:["fund administrator","fund administrators"],d:"The independent third party that values holdings, strikes NAV, and keeps the share register — the origin of almost every on-chain NAV feed, and never the issuer itself."} },
  { zh:{n:["托管行","托管人"],d:"实际保管证券或现金的持牌机构，客户资产与自有资产分账隔离——“钱到底在不在”这个问题最终指向它。"},
    en:{n:["custodian","custodians"],d:"The licensed institution that actually holds the securities or cash, segregated from its own balance sheet — where 'is the money really there' ultimately bottoms out."} },
  { zh:{n:["请求权链","请求权"],d:"从代币 → SPV/信托 → 托管账户 → 真实资产的每一环法律连接。你持有的是这条链，任一环断掉，代币就只是一串数字。"},
    en:{n:["claim chain","chain of claims"],d:"Every legal link from token → SPV/trust → custody account → the actual asset. You hold the chain; break one link and the token is just a number."} },
  { zh:{n:["清偿瀑布","瀑布"],d:"现金流按固定顺序分配的规则：先付费用、再付优先档利息，最后才轮到劣后档——出事时你排第几，全看这张表。"},
    en:{n:["waterfall"],d:"The fixed order in which cash flows are paid: fees first, then senior interest, junior last. When things go wrong, your place in this table is everything."} },
  { zh:{n:["Cede & Co."],d:"美国几乎所有上市证券的法定登记名义人（DTC 的代名人）。传统市场早就是层层受益权，链上并没有发明这个套娃。"},
    en:{n:["Cede & Co."],d:"The nominee in whose name nearly all US listed securities are legally registered (DTC's nominee). TradFi was already layers of beneficial interest; chains didn't invent the nesting."} },

  // —— 代币标准 ——
  { zh:{n:["ERC-20"],d:"同质化代币标准：一个合约里的“地址→余额”表，每一枚都一样、可自由转移——自由到装不下一只需要管准入的证券。"},
    en:{n:["ERC-20"],d:"The fungible-token standard: an 'address → balance' table where every unit is identical and freely transferable — too freely for a security that must police who holds it."} },
  { zh:{n:["ERC-721","NFT"],d:"独一无二、不可互换的代币标准，适合表示单一房产、单张票据这类“世上只有这一个”的资产。"},
    en:{n:["ERC-721","NFT","NFTs"],d:"The standard for unique, non-interchangeable tokens — a fit for one specific building or one specific note, things there is only one of."} },
  { zh:{n:["ERC-3643","T-REX"],d:"许可型证券代币标准：转账前先问合规合约“这个收币人合格吗”，不合格直接失败——把准入名单写进代币本身。"},
    en:{n:["ERC-3643","T-REX"],d:"The permissioned security-token standard: every transfer asks a compliance contract 'is this recipient eligible?' and reverts if not — the guest list lives inside the token."} },
  { zh:{n:["ERC-4626","代币化金库"],d:"生息金库的统一接口（存资产得份额、赎份额得资产），让 DeFi 协议不必为每个收益产品单独适配。"},
    en:{n:["ERC-4626","tokenized vault"],d:"A common interface for yield-bearing vaults — deposit assets for shares, redeem shares for assets — so DeFi protocols need no bespoke integration per product."} },
  { zh:{n:["ONCHAINID"],d:"ERC-3643 配套的链上身份合约：一个持有人一个身份，KYC 结果以“声明”形式挂在上面，供合规检查读取。"},
    en:{n:["ONCHAINID"],d:"The on-chain identity contract behind ERC-3643: one identity per holder, carrying KYC results as claims that compliance checks read."} },
  { zh:{n:["白名单","允许名单"],d:"通过 KYC 才被写进去的合格地址集合，是许可型代币最原始也最普遍的合规实现方式。"},
    en:{n:["whitelist","allowlist","whitelists"],d:"The set of eligible addresses admitted after KYC — the crudest and most common way permissioned tokens enforce compliance."} },
  { zh:{n:["强制转账","没收"],d:"发行方无需持有人签名即可搬走代币的权限，用于法院判决、继承、私钥丢失——也是最需要被治理约束的那个开关。"},
    en:{n:["forced transfer","forcedTransfer","clawback"],d:"The issuer's power to move tokens without the holder's signature — for court orders, inheritance, lost keys. Also the switch most in need of governance."} },
  { zh:{n:["冻结与暂停","冻结"],d:"冻结锁死单个地址（常因制裁命中或诉讼），暂停一键停掉全部转账（用于漏洞或事故）——救命开关，也是中心化程度的直接证据。"},
    en:{n:["freeze and pause","freeze","pause"],d:"Freeze locks one address (a sanctions hit, litigation); pause halts every transfer at once (an exploit, an incident). Lifelines — and direct evidence of how centralized a token is."} },
  { zh:{n:["铸造与销毁","铸造","销毁"],d:"申购时铸出新代币、赎回时销毁代币，让流通量始终等于链下真实持仓——这是供给端对账的唯一正确姿势。"},
    en:{n:["mint/burn","mint","burn"],d:"Mint on subscription, burn on redemption, so supply always equals the off-chain holdings — the only correct way to keep both sides reconciled."} },
  { zh:{n:["累积型与重定基","重定基","累积型"],d:"发收益的两条路：重定基每天增加持有人的币数（单价恒为 1，对钱包直观、对 DeFi 常是灾难），累积型让份额价格上涨（币数不变，合约友好）。"},
    en:{n:["rebase vs accrual","rebase","accumulating"],d:"Two ways to pay yield: rebasing grows everyone's unit count daily (price pinned at 1 — intuitive in a wallet, often a disaster for DeFi), while accruing lifts the share price instead (contract-friendly)."} },

  // —— 合规 ——
  { zh:{n:["KYC"],d:"Know Your Customer：核实身份、住址与资金来源，是把一个链上地址绑定到一个可追责真人的那一步。"},
    en:{n:["KYC"],d:"Know Your Customer: verifying identity, address, and source of funds — the step that binds an on-chain address to an accountable human."} },
  { zh:{n:["AML","反洗钱"],d:"Anti-Money Laundering：识别并上报可疑资金流动的制度总称，是发行方最容易踩线、罚款最重的领域。"},
    en:{n:["AML","anti-money laundering"],d:"The regime for detecting and reporting suspicious money flows — where issuers most often trip, and where the fines bite hardest."} },
  { zh:{n:["制裁筛查","OFAC","SDN"],d:"把交易对手比对美国 OFAC 等制裁名单（SDN List）；命中即必须拒绝并冻结，没有商业裁量空间。"},
    en:{n:["sanctions screening","OFAC","SDN"],d:"Checking counterparties against sanctions lists such as OFAC's SDN List. A hit means refuse and freeze — there is no commercial discretion."} },
  { zh:{n:["Reg D"],d:"美国私募豁免：不向 SEC 注册即可发行，但只能卖给合格投资者、限制转售（506(c) 允许公开宣传但须逐个核验买家）。"},
    en:{n:["Reg D"],d:"The US private-placement exemption: issue without SEC registration, but only to accredited investors and with resale limits. Rule 506(c) permits advertising if you verify every buyer."} },
  { zh:{n:["Reg S"],d:"境外发行豁免：只卖给美国境外买家即可不受美国注册要求约束，代价是要设防止“回流美国”的隔离期。"},
    en:{n:["Reg S"],d:"The offshore exemption: sell only to non-US buyers and US registration doesn't apply — at the cost of a compliance period keeping the tokens out of US hands."} },
  { zh:{n:["Reg A+"],d:"“迷你 IPO”豁免：一年最多约 7,500 万美元、可向散户公开发售，但要走 SEC 审核与持续披露。"},
    en:{n:["Reg A+"],d:"The 'mini-IPO' exemption: up to roughly $75M a year, sellable to retail — in exchange for SEC qualification and ongoing reporting."} },
  { zh:{n:["Rule 144"],d:"限制性证券的转售规则：私募买来的份额通常要持满 6–12 个月才能转手——很多 RWA 代币“买了不能马上卖”的法律根源。"},
    en:{n:["Rule 144"],d:"The resale rule for restricted securities: privately bought shares typically must be held 6–12 months first — the legal reason many RWA tokens can't be sold right away."} },
  { zh:{n:["资格声明","链上声明"],d:"由持牌机构签发、挂在链上身份上的一条可验证断言（“已过 KYC”“是合格投资者”），合规合约只读它，不碰隐私数据。"},
    en:{n:["eligibility claim","eligibility claims"],d:"A verifiable assertion issued by a licensed provider and attached to an on-chain identity ('KYC passed', 'accredited'). Compliance contracts read the claim, never the private data behind it."} },

  // —— 数据与预言机 ——
  { zh:{n:["预言机","喂价"],d:"把链下事实（价格、NAV、储备余额）搬上链的服务。链本身看不见外面，所有 RWA 的真实性最终都要过这道口子。"},
    en:{n:["oracle","oracles","price feed"],d:"The service that carries off-chain facts — prices, NAV, reserve balances — onto a chain. The chain can't see out; every RWA's truth passes through this gate."} },
  { zh:{n:["心跳更新","心跳"],d:"预言机“最长多久必须更新一次”的承诺（如 24 小时）。心跳越慢，链上那个数字越可能是昨天的。"},
    en:{n:["heartbeat","heartbeats"],d:"An oracle's promise of the longest gap between updates (say 24 hours). The slower the heartbeat, the more likely the on-chain number is yesterday's."} },
  { zh:{n:["偏差阈值"],d:"价格变动超过某个百分比就立刻推送更新的触发规则，与心跳互补：一个管“变太多”，一个管“太久没动”。"},
    en:{n:["deviation threshold","deviation thresholds"],d:"The rule that pushes an update as soon as the price moves more than X%. It complements the heartbeat: one covers 'moved too much', the other 'silent too long'."} },
  { zh:{n:["储备证明","PoR"],d:"Proof of Reserve：把托管账户余额定期喂上链，让合约能自动核对“流通量 ≤ 储备量”——它证明资产在，但不证明负债已清。"},
    en:{n:["Proof of Reserve","proof of reserve","PoR"],d:"Feeding custody balances on-chain so contracts can auto-check that supply ≤ reserves. It proves the assets exist; it says nothing about the liabilities against them."} },
  { zh:{n:["鉴证报告","鉴证"],d:"会计师对“某时点储备构成”出具的有限保证意见——比完整审计弱得多：只看一个快照，不评价内控与全期间。"},
    en:{n:["attestation","attestations"],d:"An accountant's limited-assurance opinion on reserve composition at a single moment. Far weaker than a full audit: a snapshot, with no view on controls or the whole period."} },

  // —— 市场与流动性 ——
  { zh:{n:["一级市场"],d:"直接向发行方申购或赎回的通道，按 NAV 成交、有 KYC 与起投门槛——RWA 的价格纪律基本靠它维持。"},
    en:{n:["primary market"],d:"Subscribing or redeeming directly with the issuer at NAV, behind KYC and minimums. It's what actually enforces price discipline in RWA."} },
  { zh:{n:["二级市场"],d:"持有人之间的转手交易，价格由供需决定。RWA 的二级市场往往极薄，屏幕上挂着单不代表你卖得掉。"},
    en:{n:["secondary market"],d:"Holder-to-holder trading at whatever supply and demand set. RWA secondaries are usually paper-thin — a quote on screen is not a fill."} },
  { zh:{n:["AMM","自动做市商"],d:"用恒定乘积等公式按池中储备自动报价的合约。它永远给得出价，而这恰恰对一天只变一次的 NAV 类资产极不友好。"},
    en:{n:["AMM","AMMs","automated market maker"],d:"A contract that quotes automatically from pool reserves via a formula. It always has a price — which is exactly wrong for an asset whose NAV moves once a day."} },
  { zh:{n:["订单簿"],d:"买卖双方挂价撮合的传统市场结构，价格发现更准，但需要真实做市商持续报价，否则就是一片空白。"},
    en:{n:["order book","order books"],d:"The classic venue where bids and asks are matched. Better price discovery — but it stays empty unless real market makers keep quoting."} },
  { zh:{n:["套利"],d:"二级价格偏离 NAV 时，从便宜一侧买入、到贵的一侧赎回或卖出赚差价——这条回路才是锚定真正的执行机制。"},
    en:{n:["arbitrage"],d:"When the secondary price drifts from NAV, buying the cheap side and redeeming or selling the rich side. This loop, not a promise, is what actually enforces the peg."} },
  { zh:{n:["锚定"],d:"代币价格贴住某个参考值（1 美元、1 份 NAV）。锚定从来不是承诺出来的，是可信赎回加套利撑出来的。"},
    en:{n:["peg","pegged"],d:"A token holding to a reference value ($1, one NAV share). A peg is never held up by a promise — it's held up by credible redemption plus arbitrage."} },
  { zh:{n:["脱锚"],d:"价格明显跌离锚定值。原因几乎从不在链上，而在链下：储备被冻、赎回被停、托管行出事。"},
    en:{n:["depeg","depegged"],d:"Price breaking visibly away from its anchor. The cause is almost never on-chain — it's frozen reserves, suspended redemptions, or a failed custodian bank."} },
  { zh:{n:["ATS","另类交易系统"],d:"Alternative Trading System：受 SEC 监管的非交易所撮合场所，是美国代币化证券合法二级交易目前的主要出口。"},
    en:{n:["ATS","ATSs","alternative trading system"],d:"An SEC-regulated non-exchange venue — currently the main lawful outlet for secondary trading of tokenized securities in the US."} },
  { zh:{n:["流动性幻觉"],d:"把“能在链上转账”误当成“能随时变现”。技术上可转 ≠ 市场上有买家，地产类代币是重灾区。"},
    en:{n:["liquidity illusion"],d:"Mistaking 'transferable on-chain' for 'sellable on demand'. Technical transferability is not a bid — tokenized real estate is where this hurts most."} },

  // —— 监管 ——
  { zh:{n:["SEC"],d:"美国证券交易委员会：判定某代币是否证券、并据此监管其发行与交易的主管机关，对 RWA 影响最大的单一机构。"},
    en:{n:["SEC"],d:"The US Securities and Exchange Commission: decides whether a token is a security and regulates its issuance and trading — the single most consequential body for RWA."} },
  { zh:{n:["Howey 测试","Howey"],d:"美国判定“投资合同”的四要件：出资、共同事业、期待获利、且利润主要来自他人努力——四条全中即是证券。"},
    en:{n:["Howey test","Howey"],d:"The four-part US test for an investment contract: money invested, in a common enterprise, with an expectation of profit, derived from others' efforts. All four, and it's a security."} },
  { zh:{n:["MiCA"],d:"欧盟《加密资产市场条例》：为稳定币与加密服务商建立全欧统一牌照与储备要求，是目前最完整的加密监管框架。"},
    en:{n:["MiCA"],d:"The EU's Markets in Crypto-Assets Regulation: one passportable licence plus reserve rules for stablecoins and service providers — today's most complete crypto framework."} },
  { zh:{n:["EMT","电子货币代币"],d:"MiCA 下锚定单一法币的代币类别（如欧元稳定币），须由持牌电子货币机构发行、按面值随时赎回；锚一篮子的则归为 ART。"},
    en:{n:["EMT","e-money token"],d:"MiCA's category for tokens pegged to one fiat currency: issued by a licensed e-money institution and redeemable at par on demand. Basket-referenced tokens fall under ART instead."} },
  { zh:{n:["GENIUS 法案","GENIUS Act"],d:"美国支付稳定币联邦立法：要求 1:1 高质量流动储备、月度披露与联邦或州级牌照，把稳定币从灰区搬进银行式监管。"},
    en:{n:["GENIUS Act"],d:"US federal legislation for payment stablecoins: 1:1 high-quality liquid reserves, monthly disclosure, and a federal or state licence — moving stablecoins from grey zone to bank-style supervision."} },
  { zh:{n:["MAS"],d:"新加坡金融管理局：以 Project Guardian 等试点推动机构级代币化，风格是“先在受控环境里跑，再定规则”（香港 SFC 走的是发牌路线）。"},
    en:{n:["MAS"],d:"The Monetary Authority of Singapore: drives institutional tokenization through pilots like Project Guardian — build it in a controlled setting first, write the rules after. Hong Kong's SFC leans on licensing instead."} },
  { zh:{n:["DLT 试点制度","DLT Pilot"],d:"欧盟为分布式账本证券市场设的临时豁免机制：允许在限额内暂免部分传统规则，边跑边观察。"},
    en:{n:["DLT Pilot Regime","DLT Pilot"],d:"The EU's temporary exemption regime for DLT-based securities markets: waive selected legacy rules within capped limits and watch what happens."} },
  { zh:{n:["监管沙盒"],d:"监管机构划出的受限试验区：在人数、额度与期限约束下带牌运行未成熟业务，用真实数据换未来的规则。"},
    en:{n:["regulatory sandbox"],d:"A supervised testing space where an untested business runs under caps on users, size, and time — the regulator trading a licence for real-world data."} },
  { zh:{n:["Project Guardian"],d:"MAS 牵头、多家国际银行与资管参与的代币化试点，验证许可流动性池、跨境结算与代币化基金的可行性。"},
    en:{n:["Project Guardian"],d:"The MAS-led tokenization pilot with global banks and asset managers, testing permissioned liquidity pools, cross-border settlement, and tokenized funds."} },

  // —— 产品与案例 ——
  { zh:{n:["稳定币"],d:"价值锚定法币的加密代币——其实就是第一个跑通的 RWA：链上一枚代币，链下一美元现金或短期国债。"},
    en:{n:["stablecoin","stablecoins"],d:"A crypto token pegged to a fiat currency — and in truth the first RWA that worked: one token on-chain, one dollar of cash or T-bills off it."} },
  { zh:{n:["USDC"],d:"Circle 发行的美元稳定币，储备以现金与短期国债为主、按月出鉴证；2023 年硅谷银行事件里短暂脱锚，又靠赎回通道复位。"},
    en:{n:["USDC"],d:"Circle's dollar stablecoin, reserved mainly in cash and short Treasuries with monthly attestations. It briefly depegged during the 2023 SVB week and was pulled back by redemption."} },
  { zh:{n:["USDT"],d:"Tether 发行、规模最大的美元稳定币；流动性无出其右，储备透明度则长期是争议焦点。"},
    en:{n:["USDT"],d:"Tether's dollar stablecoin, the largest by far. Unmatched liquidity; reserve transparency has been the long-running argument."} },
  { zh:{n:["BUIDL"],d:"贝莱德的代币化美元国债基金（由 Securitize 发行），仅对合格购买人开放，支持链上转账与稳定币即时赎回——机构级标杆。"},
    en:{n:["BUIDL"],d:"BlackRock's tokenized US Treasury fund, issued via Securitize: qualified purchasers only, with on-chain transfer and near-instant stablecoin redemption — the institutional benchmark."} },
  { zh:{n:["OUSG"],d:"Ondo 面向合格投资者的代币化短期国债产品，底层多为 BUIDL 等基金份额，主打机构申赎与即时流动性。"},
    en:{n:["OUSG"],d:"Ondo's tokenized short-Treasury product for accredited investors, backed largely by fund shares such as BUIDL, built around institutional subscription and instant redemption."} },
  { zh:{n:["USDY"],d:"Ondo 面向非美用户的生息代币：形式上是有国债担保的票据，价格随利息累积上涨，以此绕开美国证券定性。"},
    en:{n:["USDY"],d:"Ondo's yield-bearing token for non-US users: structurally a Treasury-backed note whose price accrues interest, sidestepping US securities classification."} },
  { zh:{n:["PAXG","代币化黄金"],d:"Paxos 发行、每枚对应伦敦金库中一金衡盎司实物金的代币，可查金条编号、可赎回实物——把金条切成克来卖。"},
    en:{n:["PAXG"],d:"Paxos's gold token: one troy ounce in a London vault per unit, with a lookup-able bar serial and physical redemption — a gold bar sliced into grams."} },
  { zh:{n:["存款代币"],d:"商业银行把自家存款负债代币化的产物：仍是受银行监管的存款，但能 7×24 在链上结算——稳定币的机构版对手。"},
    en:{n:["deposit token","deposit tokens"],d:"A commercial bank tokenizing its own deposit liability: still a regulated bank deposit, but settling on-chain around the clock — the institutional answer to stablecoins."} },
  { zh:{n:["Sky","MakerDAO"],d:"最早大规模把代币化国债纳入抵押品的 DeFi 协议，用 RWA 收益支撑其稳定币——也第一个撞上“去中心化协议依赖链下法律实体”的悖论。"},
    en:{n:["Sky","MakerDAO"],d:"The first DeFi protocol to take tokenized Treasuries as collateral at scale, backing its stablecoin with RWA yield — and the first to hit the paradox of a decentralized protocol leaning on off-chain legal entities."} },
  { zh:{n:["Centrifuge"],d:"把应收账款、贸易融资等实体信贷池代币化、分优先/劣后档接入 DeFi 的协议；早期资产池违约暴露了链下尽调的分量。"},
    en:{n:["Centrifuge"],d:"A protocol tokenizing receivables and trade-finance pools into senior/junior tranches for DeFi. Early pool defaults showed how much the off-chain underwriting really matters."} },
  { zh:{n:["Maple"],d:"链上机构借贷平台：由池代表负责尽调、发放低抵押贷款。2022 年连环违约证明真正的风险是“池代表的判断力”，不是合约。"},
    en:{n:["Maple"],d:"An on-chain institutional lending venue where pool delegates underwrite and issue undercollateralized loans. The 2022 defaults proved the real risk was the delegate's judgment, not the contract."} },
  { zh:{n:["RealT"],d:"把美国单体住宅装进 LLC 再碎片化成代币的地产平台，租金按周分发；也是“流动性幻觉”最常被引用的案例。"},
    en:{n:["RealT"],d:"A platform putting single US homes into LLCs and fractionalizing them into tokens with weekly rent distributions — and the most-cited case study in the liquidity illusion."} },
  { zh:{n:["Securitize"],d:"美国持牌转让代理兼经纪商，为 BUIDL 等产品提供发行、名册与 ATS 交易的一体化通道——RWA 的合规基础设施层。"},
    en:{n:["Securitize"],d:"A US-licensed transfer agent and broker-dealer providing issuance, share registry, and ATS trading for products like BUIDL — RWA's compliance infrastructure layer."} },
];
